# Required fields
template             = "python-lib"         # Name of the template to use (must match keys in templates.toml)
template_version     = "v0.1.3"             # Tag or branch to pin the template
<<<<<<< HEAD
template_description = "{{ project_name }}"
project_name         = "{{ project_name }}" # Directory and placeholder name for the new project
=======
template_description = "cntkn"
project_name         = "cntkn" # Directory and placeholder name for the new project
>>>>>>> 6c25a8e (initial commit)

# Optional: components to include (order matters)
[[components]]
  name    = "cli"           # Sub-component in the template
  version = "0.1.0"         # Version of that component
  options = { docs = true } # Any feature flags for this component

# Optional: global feature toggles
[features]
  docs = false
[metadata]
  author  = "Jane Doe"
  license = "MIT"
[init]
  commands = [
    "uv sync",
    "ruff check .",
    "ruff format .",
    "pytest --maxfail=1 --disable-warnings -q",
  ]
